<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerUserController',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2021-03-02 07:00:28',
                'updated_at' => '2021-03-02 07:00:28',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2021-03-02 07:00:28',
                'updated_at' => '2021-03-02 07:00:28',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerRoleController',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2021-03-02 07:00:28',
                'updated_at' => '2021-03-02 07:00:28',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'categories',
                'slug' => 'categories',
                'display_name_singular' => 'Category',
                'display_name_plural' => 'Categories',
                'icon' => 'voyager-categories',
                'model_name' => 'TCG\\Voyager\\Models\\Category',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2021-03-02 07:00:29',
                'updated_at' => '2021-03-02 07:00:29',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'posts',
                'slug' => 'posts',
                'display_name_singular' => 'Post',
                'display_name_plural' => 'Posts',
                'icon' => 'voyager-news',
                'model_name' => 'TCG\\Voyager\\Models\\Post',
                'policy_name' => 'TCG\\Voyager\\Policies\\PostPolicy',
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2021-03-02 07:00:29',
                'updated_at' => '2021-03-02 07:00:29',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'pages',
                'slug' => 'pages',
                'display_name_singular' => 'Page',
                'display_name_plural' => 'Pages',
                'icon' => 'voyager-file-text',
                'model_name' => 'TCG\\Voyager\\Models\\Page',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2021-03-02 07:00:29',
                'updated_at' => '2021-03-02 07:00:29',
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'orders',
                'slug' => 'orders',
                'display_name_singular' => 'Order',
                'display_name_plural' => 'Orders',
                'icon' => 'voyager-buy',
                'model_name' => 'App\\Models\\Order',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-03-02 07:44:11',
                'updated_at' => '2021-03-02 08:39:38',
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'comments',
                'slug' => 'comments',
                'display_name_singular' => 'Comment',
                'display_name_plural' => 'Comments',
                'icon' => 'voyager-bubble',
                'model_name' => 'App\\Models\\Comment',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2021-06-18 17:22:03',
                'updated_at' => '2021-06-18 17:22:03',
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'events',
                'slug' => 'events',
                'display_name_singular' => 'Event',
                'display_name_plural' => 'Events',
                'icon' => 'voyager-news',
                'model_name' => 'App\\Models\\Event',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2021-06-18 17:23:40',
                'updated_at' => '2021-06-18 17:23:40',
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'products',
                'slug' => 'products',
                'display_name_singular' => 'Product',
                'display_name_plural' => 'Products',
                'icon' => 'voyager-watch',
                'model_name' => 'App\\Models\\Product',
                'policy_name' => '\\App\\Policies\\ProductPolicy',
                'controller' => 'App\\Http\\Controllers\\Admin\\ProductController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-06-18 17:27:08',
                'updated_at' => '2021-06-18 17:30:56',
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'shops',
                'slug' => 'shops',
                'display_name_singular' => 'Shop',
                'display_name_plural' => 'Shops',
                'icon' => 'voyager-shop',
                'model_name' => 'App\\Models\\Shop',
                'policy_name' => '\\App\\Policies\\ShopPolicy',
                'controller' => 'App\\Http\\Controllers\\Admin\\ShopController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2021-06-18 17:32:11',
                'updated_at' => '2021-06-18 17:33:12',
            ),
            11 => 
            array (
                'id' => 14,
                'name' => 'sub_orders',
                'slug' => 'sub-orders',
                'display_name_singular' => 'Sub Order',
                'display_name_plural' => 'Sub Orders',
                'icon' => 'voyager-file-text',
                'model_name' => 'App\\Models\\SubOrder',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2021-06-18 17:34:18',
                'updated_at' => '2021-06-18 17:34:18',
            ),
            12 => 
            array (
                'id' => 15,
                'name' => 'transactions',
                'slug' => 'transactions',
                'display_name_singular' => 'Transaction',
                'display_name_plural' => 'Transactions',
                'icon' => 'voyager-dollar',
                'model_name' => 'App\\Models\\Transaction',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2021-06-18 17:35:37',
                'updated_at' => '2021-06-18 17:35:37',
            ),
            13 => 
            array (
                'id' => 16,
                'name' => 'slideshows',
                'slug' => 'slideshows',
                'display_name_singular' => 'Slideshow',
                'display_name_plural' => 'Slideshows',
                'icon' => 'voyager-images',
                'model_name' => 'App\\Models\\Slideshow',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2021-06-18 17:36:44',
                'updated_at' => '2021-06-18 17:36:44',
            ),
            14 => 
            array (
                'id' => 17,
                'name' => 'coupons',
                'slug' => 'coupons',
                'display_name_singular' => 'Coupon',
                'display_name_plural' => 'Coupons',
                'icon' => 'voyager-gift',
                'model_name' => 'App\\Models\\Coupon',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2021-06-18 17:37:31',
                'updated_at' => '2021-06-18 17:37:31',
            ),
        ));
        
        
    }
}