<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'shop_id' => NULL,
                'cat_id' => 8,
                'child_cat_id' => 3,
                'name' => 'Aut dolores et.',
                'slug' => 'omnis-alias-commodi-ea-quia-sunt',
                'summary' => 'Nobis velit est ut fuga cupiditate repellat autem minima soluta.',
                'description' => 'Molestiae soluta sequi quibusdam nisi. Et in exercitationem corporis enim voluptatibus. Similique assumenda expedita eum fugiat repellat ut sapiente. Inventore cum nulla aperiam necessitatibus id non.',
                'image' => 'https://via.placeholder.com/400x200.png/00cc88?text=nam',
                'images' => 'https://via.placeholder.com/400x200.png/00bbaa?text=repudiandae',
                'price' => 98.1,
                'stock' => 10,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:43',
                'updated_at' => '2021-06-18 17:01:43',
            ),
            1 => 
            array (
                'id' => 2,
                'shop_id' => NULL,
                'cat_id' => 11,
                'child_cat_id' => 9,
                'name' => 'Laboriosam voluptatem aspernatur.',
                'slug' => 'nihil-ducimus-sapiente-maiores-itaque',
                'summary' => 'Consequatur dolor voluptas deserunt dolorum officia cumque aliquam veniam ducimus.',
                'description' => 'Repellat aut sed pariatur quia et hic porro. Ab iste id maiores ut. Inventore laborum suscipit velit. Est molestias et accusantium vero qui perferendis tempore.',
                'image' => 'https://via.placeholder.com/400x200.png/008866?text=saepe',
                'images' => 'https://via.placeholder.com/400x200.png/0066dd?text=numquam',
                'price' => 52.33,
                'stock' => 10,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:43',
                'updated_at' => '2021-06-18 17:01:43',
            ),
            2 => 
            array (
                'id' => 3,
                'shop_id' => NULL,
                'cat_id' => 10,
                'child_cat_id' => 13,
                'name' => 'Sed id et.',
                'slug' => 'qui-harum-natus-rem-id-facere',
                'summary' => 'Animi omnis quo fugit sit sed vel iure aut similique.',
                'description' => 'Fugit sit veritatis in repellendus qui. Modi aliquam minima consequatur neque temporibus ipsum. Quas qui nostrum nisi fugiat ut.',
                'image' => 'https://via.placeholder.com/400x200.png/00ddbb?text=ipsa',
                'images' => 'https://via.placeholder.com/400x200.png/005588?text=qui',
                'price' => 94.32,
                'stock' => 6,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:43',
                'updated_at' => '2021-06-18 17:01:43',
            ),
            3 => 
            array (
                'id' => 4,
                'shop_id' => NULL,
                'cat_id' => 16,
                'child_cat_id' => 20,
                'name' => 'Maxime perspiciatis quaerat.',
                'slug' => 'temporibus-dolorem-cum-sequi-et',
                'summary' => 'Debitis id nostrum et molestiae velit excepturi molestias architecto repellat.',
                'description' => 'Officia sequi molestiae aliquam odio ipsum praesentium. Facilis molestias veniam id libero minus. Culpa impedit dolorem consequatur quos possimus esse. Voluptates in quaerat nostrum.',
                'image' => 'https://via.placeholder.com/400x200.png/00ffaa?text=tempore',
                'images' => 'https://via.placeholder.com/400x200.png/00aa77?text=omnis',
                'price' => 82.66,
                'stock' => 4,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            4 => 
            array (
                'id' => 5,
                'shop_id' => NULL,
                'cat_id' => 11,
                'child_cat_id' => 17,
                'name' => 'Nesciunt non doloribus.',
                'slug' => 'facere-consectetur-quo-ullam-expedita-ut',
                'summary' => 'Nulla quia blanditiis deleniti et consequuntur ut suscipit animi corrupti.',
                'description' => 'Velit beatae consequatur quia omnis. Et similique rerum repudiandae quia quia ad modi. Ullam odit voluptatibus laboriosam perferendis. Itaque vero magnam ut recusandae.',
                'image' => 'https://via.placeholder.com/400x200.png/00bbdd?text=est',
                'images' => 'https://via.placeholder.com/400x200.png/00ff88?text=non',
                'price' => 33.48,
                'stock' => 2,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            5 => 
            array (
                'id' => 6,
                'shop_id' => NULL,
                'cat_id' => 5,
                'child_cat_id' => 7,
                'name' => 'Nemo ea porro.',
                'slug' => 'at-qui-aut-voluptas-qui-facere-inventore-sit',
                'summary' => 'In maxime porro aut inventore repellendus quasi perspiciatis aut et.',
                'description' => 'Non eius eos deserunt ut aspernatur. Ut similique culpa nostrum accusamus nesciunt distinctio omnis. Hic qui minima optio voluptatem id.',
                'image' => 'https://via.placeholder.com/400x200.png/0033bb?text=est',
                'images' => 'https://via.placeholder.com/400x200.png/0011dd?text=tenetur',
                'price' => 47.1,
                'stock' => 8,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            6 => 
            array (
                'id' => 7,
                'shop_id' => NULL,
                'cat_id' => 6,
                'child_cat_id' => 19,
                'name' => 'Beatae ut qui.',
                'slug' => 'eos-rerum-qui-enim-rem',
                'summary' => 'Ea voluptas molestiae nihil dicta quae omnis aut est eum.',
                'description' => 'Blanditiis pariatur et et et possimus et ut. Voluptas dolor enim voluptatem sit. Quia fugit modi nulla qui minus ipsam omnis.',
                'image' => 'https://via.placeholder.com/400x200.png/00dd00?text=aut',
                'images' => 'https://via.placeholder.com/400x200.png/001166?text=dolor',
                'price' => 81.55,
                'stock' => 5,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            7 => 
            array (
                'id' => 8,
                'shop_id' => NULL,
                'cat_id' => 4,
                'child_cat_id' => 20,
                'name' => 'Voluptatem ipsa aspernatur.',
                'slug' => 'corrupti-est-quis-sunt-neque-laborum',
                'summary' => 'Non nihil libero adipisci quisquam repudiandae autem velit nostrum quae.',
                'description' => 'Non possimus cupiditate consequuntur quae enim quasi. Omnis rerum eaque voluptatem rerum commodi iste error. Sint commodi non voluptas ipsam quia.',
                'image' => 'https://via.placeholder.com/400x200.png/00ff99?text=consequuntur',
                'images' => 'https://via.placeholder.com/400x200.png/00aa00?text=quibusdam',
                'price' => 47.68,
                'stock' => 3,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            8 => 
            array (
                'id' => 9,
                'shop_id' => NULL,
                'cat_id' => 1,
                'child_cat_id' => 3,
                'name' => 'Eum aut aspernatur.',
                'slug' => 'non-ab-voluptatum-saepe-facilis-at-error',
                'summary' => 'Voluptates quia qui in possimus ut est omnis dicta ducimus.',
                'description' => 'Veritatis quae tempora est repellat voluptas eveniet reiciendis nam. Magnam voluptatibus harum pariatur. Sapiente aut sunt molestiae repellendus facilis. Rerum doloribus ut recusandae et vero molestiae minus. Totam placeat incidunt est velit voluptatem.',
                'image' => 'https://via.placeholder.com/400x200.png/00cc33?text=voluptas',
                'images' => 'https://via.placeholder.com/400x200.png/001100?text=laborum',
                'price' => 74.93,
                'stock' => 7,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            9 => 
            array (
                'id' => 10,
                'shop_id' => NULL,
                'cat_id' => 5,
                'child_cat_id' => 18,
                'name' => 'Dicta et ex.',
                'slug' => 'eligendi-nisi-dolore-rerum-consectetur-at-reprehenderit',
                'summary' => 'Nisi saepe dignissimos dolor voluptatibus molestiae iure ut qui culpa.',
                'description' => 'Ut corporis cum distinctio est eos enim. Ut repudiandae quo doloremque eaque voluptas quia. Repudiandae omnis et minima unde a ipsa ipsam sed. Nesciunt quia reiciendis laboriosam quasi autem.',
                'image' => 'https://via.placeholder.com/400x200.png/003399?text=sunt',
                'images' => 'https://via.placeholder.com/400x200.png/0077cc?text=natus',
                'price' => 37.04,
                'stock' => 5,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            10 => 
            array (
                'id' => 11,
                'shop_id' => NULL,
                'cat_id' => 12,
                'child_cat_id' => 3,
                'name' => 'Quis nemo qui.',
                'slug' => 'nobis-quod-quibusdam-numquam-nihil-quibusdam-tenetur',
                'summary' => 'Voluptatem aperiam ducimus vero quasi aut ipsum ullam omnis officiis.',
                'description' => 'Tenetur sunt harum odit. Sequi quasi sequi quisquam laboriosam occaecati. Vero atque facilis ea qui.',
                'image' => 'https://via.placeholder.com/400x200.png/009988?text=corrupti',
                'images' => 'https://via.placeholder.com/400x200.png/005555?text=quos',
                'price' => 86.48,
                'stock' => 8,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            11 => 
            array (
                'id' => 12,
                'shop_id' => NULL,
                'cat_id' => 14,
                'child_cat_id' => 17,
                'name' => 'Facere eos corrupti.',
                'slug' => 'itaque-beatae-eum-vel-quidem-minima',
                'summary' => 'Sit perferendis id tempora voluptate ut quis et velit in.',
                'description' => 'Ipsum quas perferendis dolor aut. Itaque quo optio quasi sed. Dicta asperiores sit saepe nihil dolorum reprehenderit.',
                'image' => 'https://via.placeholder.com/400x200.png/0055ee?text=ipsum',
                'images' => 'https://via.placeholder.com/400x200.png/0022cc?text=placeat',
                'price' => 10.89,
                'stock' => 10,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            12 => 
            array (
                'id' => 13,
                'shop_id' => NULL,
                'cat_id' => 6,
                'child_cat_id' => 9,
                'name' => 'Itaque qui voluptatem.',
                'slug' => 'vero-iste-dolore-expedita-consequatur-iste-accusamus',
                'summary' => 'Voluptatibus dolor voluptatum et cum impedit commodi eius maiores tenetur.',
                'description' => 'Nihil dolorem consequuntur ea exercitationem. Aut non officia aspernatur enim. At libero consequatur distinctio sunt facilis.',
                'image' => 'https://via.placeholder.com/400x200.png/0055aa?text=est',
                'images' => 'https://via.placeholder.com/400x200.png/00dddd?text=non',
                'price' => 31.18,
                'stock' => 3,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            13 => 
            array (
                'id' => 14,
                'shop_id' => NULL,
                'cat_id' => 11,
                'child_cat_id' => 19,
                'name' => 'Sequi officiis sequi.',
                'slug' => 'exercitationem-et-explicabo-repellat-et-corrupti-dignissimos',
                'summary' => 'Quia non illo accusantium necessitatibus quasi odit incidunt non consectetur.',
                'description' => 'Et non non repellendus accusamus inventore. Ex sed repellendus eum nostrum nisi nobis. Odio adipisci eum nemo sit numquam. Vitae excepturi distinctio et dolorem sunt adipisci sed repudiandae.',
                'image' => 'https://via.placeholder.com/400x200.png/006677?text=reprehenderit',
                'images' => 'https://via.placeholder.com/400x200.png/004477?text=asperiores',
                'price' => 50.94,
                'stock' => 3,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            14 => 
            array (
                'id' => 15,
                'shop_id' => NULL,
                'cat_id' => 10,
                'child_cat_id' => 9,
                'name' => 'Dolorum optio debitis.',
                'slug' => 'at-ad-pariatur-tempora-ut-sint',
                'summary' => 'Quidem delectus quia molestiae consequuntur veniam et ducimus voluptatibus ut.',
                'description' => 'Commodi iure fugit temporibus inventore exercitationem. Sunt voluptatum et quod unde natus voluptate magni exercitationem. Minima numquam quos rerum et consequatur. Eligendi sed nostrum corporis dolorem.',
                'image' => 'https://via.placeholder.com/400x200.png/0088bb?text=ratione',
                'images' => 'https://via.placeholder.com/400x200.png/00bbff?text=inventore',
                'price' => 45.48,
                'stock' => 2,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            15 => 
            array (
                'id' => 16,
                'shop_id' => NULL,
                'cat_id' => 8,
                'child_cat_id' => 20,
                'name' => 'Molestiae qui saepe.',
                'slug' => 'quaerat-beatae-labore-esse',
                'summary' => 'Quia eos voluptas qui aut officia dolores nesciunt dolor ut.',
                'description' => 'Assumenda explicabo vero consequatur eius eum. Nostrum dignissimos consectetur rem ipsa. Provident optio tenetur et exercitationem quae et. Voluptas sint voluptas ad voluptatem aspernatur qui accusantium. Quae doloribus autem quam exercitationem voluptate sed quam.',
                'image' => 'https://via.placeholder.com/400x200.png/009988?text=aut',
                'images' => 'https://via.placeholder.com/400x200.png/001188?text=eum',
                'price' => 96.68,
                'stock' => 10,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            16 => 
            array (
                'id' => 17,
                'shop_id' => NULL,
                'cat_id' => 5,
                'child_cat_id' => 18,
                'name' => 'Animi autem impedit.',
                'slug' => 'necessitatibus-quam-aut-dolores-sed-tenetur',
                'summary' => 'Nulla hic modi saepe recusandae commodi est consequuntur est aliquid.',
                'description' => 'Quo praesentium qui molestiae. Ipsum deleniti enim nisi labore ullam totam. Iure nobis fugit eos numquam rerum non. Ea quis qui aut nobis incidunt ut cumque.',
                'image' => 'https://via.placeholder.com/400x200.png/00aaff?text=quibusdam',
                'images' => 'https://via.placeholder.com/400x200.png/003399?text=sed',
                'price' => 71.6,
                'stock' => 2,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            17 => 
            array (
                'id' => 18,
                'shop_id' => NULL,
                'cat_id' => 1,
                'child_cat_id' => 20,
                'name' => 'Cum quia consequatur.',
                'slug' => 'doloribus-aliquid-labore-veritatis-perspiciatis-explicabo-qui-rerum',
                'summary' => 'Eligendi dolorum quaerat doloribus mollitia omnis eligendi exercitationem dolor sequi.',
                'description' => 'Ut quo nam non qui. Itaque ut voluptates repellat aut delectus. Perferendis qui autem quia dolor illo consequatur laudantium.',
                'image' => 'https://via.placeholder.com/400x200.png/004466?text=doloribus',
                'images' => 'https://via.placeholder.com/400x200.png/00ee44?text=dolorum',
                'price' => 35.26,
                'stock' => 9,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            18 => 
            array (
                'id' => 19,
                'shop_id' => NULL,
                'cat_id' => 5,
                'child_cat_id' => 20,
                'name' => 'Quo cumque ea.',
                'slug' => 'pariatur-eveniet-culpa-libero-ea',
                'summary' => 'Ab voluptatem et omnis et tempora totam facere ipsa optio.',
                'description' => 'Et provident sed consectetur maiores sint corrupti aut odit. Et laudantium ea quidem ut vitae molestiae. Hic et hic ut temporibus et. Rem modi et corrupti velit quia sit ab.',
                'image' => 'https://via.placeholder.com/400x200.png/008877?text=est',
                'images' => 'https://via.placeholder.com/400x200.png/00ff77?text=et',
                'price' => 30.21,
                'stock' => 7,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            19 => 
            array (
                'id' => 20,
                'shop_id' => NULL,
                'cat_id' => 14,
                'child_cat_id' => 9,
                'name' => 'Laborum ex sit.',
                'slug' => 'sit-non-eum-aperiam-id',
                'summary' => 'Ratione architecto aspernatur laudantium maiores qui quas fugiat distinctio id.',
                'description' => 'Minus minima aut illo a laboriosam cumque enim. Iure sed consequatur mollitia aperiam commodi. Tempore et esse deleniti voluptatibus nesciunt et quia. Impedit illo delectus repellat consequatur consequatur.',
                'image' => 'https://via.placeholder.com/400x200.png/008866?text=quibusdam',
                'images' => 'https://via.placeholder.com/400x200.png/003355?text=nesciunt',
                'price' => 22.72,
                'stock' => 7,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            20 => 
            array (
                'id' => 21,
                'shop_id' => NULL,
                'cat_id' => 8,
                'child_cat_id' => 19,
                'name' => 'Quo beatae quis.',
                'slug' => 'sit-earum-consequatur-provident-itaque-sit',
                'summary' => 'Enim rerum omnis unde saepe explicabo numquam maxime magni tempore.',
                'description' => 'Et voluptatem vel dolorem totam cum aut. Magnam animi qui ut voluptatem. Ea facilis rem accusamus commodi pariatur voluptates ut.',
                'image' => 'https://via.placeholder.com/400x200.png/00ee11?text=eum',
                'images' => 'https://via.placeholder.com/400x200.png/00ddee?text=maxime',
                'price' => 19.18,
                'stock' => 3,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            21 => 
            array (
                'id' => 22,
                'shop_id' => NULL,
                'cat_id' => 16,
                'child_cat_id' => 13,
                'name' => 'Officiis quis perferendis.',
                'slug' => 'consequuntur-dolor-alias-vitae-architecto-accusamus-et',
                'summary' => 'Aut qui exercitationem consectetur et velit rem sunt similique ut.',
                'description' => 'Et et eos sit amet tempora totam velit eius. Voluptas repudiandae eos dolorem laudantium ut delectus. Odit quas nisi aut esse animi facere harum. Rerum deleniti error pariatur labore eius.',
                'image' => 'https://via.placeholder.com/400x200.png/0011bb?text=magnam',
                'images' => 'https://via.placeholder.com/400x200.png/004455?text=corporis',
                'price' => 62.61,
                'stock' => 3,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            22 => 
            array (
                'id' => 23,
                'shop_id' => NULL,
                'cat_id' => 6,
                'child_cat_id' => 17,
                'name' => 'At ex ut.',
                'slug' => 'totam-quia-neque-velit-quis-a-harum-dolorum',
                'summary' => 'Autem enim mollitia provident minima iure culpa voluptas quibusdam iusto.',
                'description' => 'Blanditiis minima illum repellat odio rerum. Laborum hic repellat cum explicabo nesciunt. Odit dolores fugit praesentium dolores veniam blanditiis mollitia.',
                'image' => 'https://via.placeholder.com/400x200.png/0011cc?text=ut',
                'images' => 'https://via.placeholder.com/400x200.png/00cccc?text=error',
                'price' => 15.48,
                'stock' => 7,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            23 => 
            array (
                'id' => 24,
                'shop_id' => NULL,
                'cat_id' => 4,
                'child_cat_id' => 17,
                'name' => 'Porro aut voluptatem.',
                'slug' => 'id-beatae-voluptas-reiciendis',
                'summary' => 'Incidunt unde in dolores assumenda fugit voluptatem id soluta et.',
                'description' => 'Veritatis voluptas ea optio. Odit et voluptatem dolor quis. Velit a ducimus sed sunt pariatur.',
                'image' => 'https://via.placeholder.com/400x200.png/002299?text=harum',
                'images' => 'https://via.placeholder.com/400x200.png/001111?text=omnis',
                'price' => 99.89,
                'stock' => 4,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            24 => 
            array (
                'id' => 25,
                'shop_id' => NULL,
                'cat_id' => 16,
                'child_cat_id' => 19,
                'name' => 'Quia illo non.',
                'slug' => 'et-quos-alias-debitis-dolorem-hic-aut-qui-magnam',
                'summary' => 'Architecto delectus quibusdam adipisci est expedita aperiam non sequi in.',
                'description' => 'Voluptatibus eaque provident exercitationem minima. Totam at voluptatibus quae et exercitationem. Veniam rerum et molestiae cumque quia autem deleniti.',
                'image' => 'https://via.placeholder.com/400x200.png/00ee44?text=cum',
                'images' => 'https://via.placeholder.com/400x200.png/00dd00?text=ratione',
                'price' => 82.55,
                'stock' => 3,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            25 => 
            array (
                'id' => 26,
                'shop_id' => NULL,
                'cat_id' => 11,
                'child_cat_id' => 9,
                'name' => 'Molestiae vero id.',
                'slug' => 'voluptatem-tempora-temporibus-et-ea',
                'summary' => 'Voluptatem totam recusandae est aliquid maxime laborum odit corporis qui.',
                'description' => 'Maxime facere placeat voluptatum cumque. Eum eligendi est nesciunt. Saepe minus veniam eum et molestias rerum.',
                'image' => 'https://via.placeholder.com/400x200.png/0011cc?text=ex',
                'images' => 'https://via.placeholder.com/400x200.png/0066ee?text=et',
                'price' => 22.17,
                'stock' => 4,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            26 => 
            array (
                'id' => 27,
                'shop_id' => NULL,
                'cat_id' => 8,
                'child_cat_id' => 20,
                'name' => 'Dolores eos ab.',
                'slug' => 'minus-magni-voluptate-quia',
                'summary' => 'Voluptatem explicabo atque laudantium velit nihil labore aperiam recusandae voluptatem.',
                'description' => 'Tenetur sequi quia rerum fugit amet iusto doloremque nihil. Qui ea vel quia dolor rem qui. Consectetur est ea doloribus ut praesentium minus velit. Autem quas sed impedit laborum et nobis sunt veritatis.',
                'image' => 'https://via.placeholder.com/400x200.png/00cc88?text=totam',
                'images' => 'https://via.placeholder.com/400x200.png/00ccaa?text=voluptatem',
                'price' => 24.95,
                'stock' => 10,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            27 => 
            array (
                'id' => 28,
                'shop_id' => NULL,
                'cat_id' => 14,
                'child_cat_id' => 20,
                'name' => 'Dolor occaecati aut.',
                'slug' => 'voluptas-voluptate-tempore-voluptatem-sed-suscipit',
                'summary' => 'Ut sed iusto qui in aut natus dicta sed maxime.',
                'description' => 'Aut omnis ea vero eaque voluptatibus ab distinctio. Nesciunt nemo possimus esse dicta. Eum tempore aut voluptatum earum repellat consequatur. Rem sit consequatur voluptates voluptatem velit nihil.',
                'image' => 'https://via.placeholder.com/400x200.png/007733?text=reiciendis',
                'images' => 'https://via.placeholder.com/400x200.png/005544?text=quidem',
                'price' => 75.65,
                'stock' => 4,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            28 => 
            array (
                'id' => 29,
                'shop_id' => NULL,
                'cat_id' => 11,
                'child_cat_id' => 3,
                'name' => 'Quod repellat illum.',
                'slug' => 'porro-ex-doloribus-quia-eveniet-repellat-consequatur-ut',
                'summary' => 'Non commodi aliquid earum ullam quod accusantium eos a quibusdam.',
                'description' => 'Dolorem qui magnam nisi eum voluptatum voluptatem non. Sapiente fugit et possimus adipisci. Ad corporis sit distinctio aut libero.',
                'image' => 'https://via.placeholder.com/400x200.png/004444?text=id',
                'images' => 'https://via.placeholder.com/400x200.png/006688?text=officia',
                'price' => 38.18,
                'stock' => 6,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            29 => 
            array (
                'id' => 30,
                'shop_id' => NULL,
                'cat_id' => 6,
                'child_cat_id' => 20,
                'name' => 'Eos sunt ea.',
                'slug' => 'rem-ut-sit-deleniti-sequi-porro-nihil',
                'summary' => 'Sunt ipsam soluta dolorem dolorum alias eius nihil fuga voluptatem.',
                'description' => 'Et sint eum fugit et. Vero voluptas sunt earum vero. Reiciendis maxime et nemo error reprehenderit qui possimus. Totam est neque molestiae nihil inventore itaque.',
                'image' => 'https://via.placeholder.com/400x200.png/00ff66?text=voluptates',
                'images' => 'https://via.placeholder.com/400x200.png/003377?text=sed',
                'price' => 41.42,
                'stock' => 8,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            30 => 
            array (
                'id' => 31,
                'shop_id' => NULL,
                'cat_id' => 11,
                'child_cat_id' => 7,
                'name' => 'Sed et nostrum.',
                'slug' => 'perferendis-minima-perferendis-sed-sed-iste-ea-quia',
                'summary' => 'Reiciendis alias ut unde et nihil voluptatem consequatur beatae soluta.',
                'description' => 'Officiis sint aliquam eum enim vel pariatur voluptatem. Sunt sit voluptas qui sed magni. Provident ab rerum quam fuga harum et doloremque.',
                'image' => 'https://via.placeholder.com/400x200.png/0033aa?text=velit',
                'images' => 'https://via.placeholder.com/400x200.png/0000aa?text=dolorum',
                'price' => 53.07,
                'stock' => 2,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            31 => 
            array (
                'id' => 32,
                'shop_id' => NULL,
                'cat_id' => 16,
                'child_cat_id' => 20,
                'name' => 'Debitis aspernatur fugit.',
                'slug' => 'illum-et-quia-laudantium-omnis',
                'summary' => 'Assumenda qui magni consequatur quam non voluptates provident aut odio.',
                'description' => 'Veniam illum ipsam dolor perspiciatis. Odit omnis possimus corrupti. Est commodi laudantium accusamus ratione ut. Sunt facere cumque maxime totam.',
                'image' => 'https://via.placeholder.com/400x200.png/009977?text=et',
                'images' => 'https://via.placeholder.com/400x200.png/0022ee?text=enim',
                'price' => 77.68,
                'stock' => 9,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            32 => 
            array (
                'id' => 33,
                'shop_id' => NULL,
                'cat_id' => 16,
                'child_cat_id' => 2,
                'name' => 'Laudantium totam temporibus.',
                'slug' => 'aspernatur-rerum-quo-voluptatem',
                'summary' => 'Tempora ea rerum est vitae modi voluptatem dignissimos eveniet doloribus.',
                'description' => 'Quia numquam quaerat soluta doloremque recusandae ducimus et. Reprehenderit exercitationem est ut ducimus voluptatem occaecati. Illum ducimus veritatis quo.',
                'image' => 'https://via.placeholder.com/400x200.png/00dd66?text=est',
                'images' => 'https://via.placeholder.com/400x200.png/00ff11?text=sit',
                'price' => 47.01,
                'stock' => 3,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            33 => 
            array (
                'id' => 34,
                'shop_id' => NULL,
                'cat_id' => 4,
                'child_cat_id' => 17,
                'name' => 'Nobis amet qui.',
                'slug' => 'qui-non-veniam-et-dolor-reiciendis',
                'summary' => 'Laboriosam voluptas officia id occaecati iusto reiciendis omnis qui molestiae.',
                'description' => 'Voluptatem et blanditiis sint neque sed voluptatem. Animi odit dolorum ad sunt mollitia sit. Ratione id quam corporis fugit dolores. Fugiat occaecati perferendis et qui delectus voluptatem ex.',
                'image' => 'https://via.placeholder.com/400x200.png/00bbcc?text=reiciendis',
                'images' => 'https://via.placeholder.com/400x200.png/00ffbb?text=odio',
                'price' => 75.23,
                'stock' => 8,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            34 => 
            array (
                'id' => 35,
                'shop_id' => NULL,
                'cat_id' => 5,
                'child_cat_id' => 20,
                'name' => 'Dolorem odit neque.',
                'slug' => 'quae-cumque-amet-neque-asperiores-nulla-placeat',
                'summary' => 'Ut ut eum cupiditate sapiente laborum laboriosam repellendus consequatur rerum.',
                'description' => 'Mollitia accusamus corrupti nam incidunt. Placeat pariatur et non voluptatibus nihil.',
                'image' => 'https://via.placeholder.com/400x200.png/008833?text=ut',
                'images' => 'https://via.placeholder.com/400x200.png/0077bb?text=autem',
                'price' => 87.95,
                'stock' => 5,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            35 => 
            array (
                'id' => 36,
                'shop_id' => NULL,
                'cat_id' => 1,
                'child_cat_id' => 7,
                'name' => 'Eveniet illum id.',
                'slug' => 'ad-ut-dolor-omnis-enim-explicabo',
                'summary' => 'Quae maiores eum odio labore ut praesentium eos omnis repellat.',
                'description' => 'Alias tenetur rem sint explicabo culpa nisi. Ut architecto amet fugiat nesciunt distinctio nemo cumque ducimus. Fuga dolorem quo odio vel pariatur ut pariatur.',
                'image' => 'https://via.placeholder.com/400x200.png/002255?text=enim',
                'images' => 'https://via.placeholder.com/400x200.png/0077cc?text=quis',
                'price' => 88.97,
                'stock' => 2,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            36 => 
            array (
                'id' => 37,
                'shop_id' => NULL,
                'cat_id' => 4,
                'child_cat_id' => 7,
                'name' => 'Repudiandae fuga reiciendis.',
                'slug' => 'asperiores-aliquam-eos-qui-velit',
                'summary' => 'Dolore omnis rerum accusantium ut ut consequatur totam voluptatem ad.',
                'description' => 'Blanditiis qui vel sequi veniam nemo. Animi fugiat qui neque repudiandae similique. Fuga cumque qui aut omnis doloribus ea pariatur. Pariatur porro et quaerat.',
                'image' => 'https://via.placeholder.com/400x200.png/001144?text=facilis',
                'images' => 'https://via.placeholder.com/400x200.png/009999?text=quibusdam',
                'price' => 99.26,
                'stock' => 3,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            37 => 
            array (
                'id' => 38,
                'shop_id' => NULL,
                'cat_id' => 6,
                'child_cat_id' => 2,
                'name' => 'Ratione dolores non.',
                'slug' => 'similique-veniam-accusamus-illum-sit-eum-ut-quia-est',
                'summary' => 'Nemo ut praesentium sit ipsum alias adipisci molestiae sint fugit.',
                'description' => 'Eaque veritatis voluptatem et quia earum. Est molestias id sit ea maxime et. Nemo velit esse vitae consectetur blanditiis cupiditate. Et dolorem molestias debitis temporibus.',
                'image' => 'https://via.placeholder.com/400x200.png/0011aa?text=expedita',
                'images' => 'https://via.placeholder.com/400x200.png/00dd44?text=odit',
                'price' => 56.58,
                'stock' => 3,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            38 => 
            array (
                'id' => 39,
                'shop_id' => NULL,
                'cat_id' => 14,
                'child_cat_id' => 2,
                'name' => 'Commodi non nostrum.',
                'slug' => 'a-aut-magnam-consequuntur-eos-animi-labore',
                'summary' => 'Velit eum nulla doloremque aut quam eum commodi ipsa doloribus.',
                'description' => 'Est unde laudantium ducimus expedita. Velit magni ratione similique dolorem eligendi. Velit ut suscipit nihil veritatis mollitia aliquid. Non qui voluptas natus enim rerum aut.',
                'image' => 'https://via.placeholder.com/400x200.png/004455?text=quo',
                'images' => 'https://via.placeholder.com/400x200.png/00dd66?text=sunt',
                'price' => 25.27,
                'stock' => 7,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            39 => 
            array (
                'id' => 40,
                'shop_id' => NULL,
                'cat_id' => 6,
                'child_cat_id' => 17,
                'name' => 'Unde corporis error.',
                'slug' => 'omnis-repellendus-minima-voluptatibus-et-occaecati-consequatur',
                'summary' => 'Vel aliquam asperiores quibusdam maiores impedit voluptatem aliquam quia nihil.',
                'description' => 'Eaque aut vel sit officia odio ut omnis. Autem aliquam perferendis nihil quo sit rerum deleniti quis. Aut aperiam mollitia ad hic omnis.',
                'image' => 'https://via.placeholder.com/400x200.png/005555?text=iure',
                'images' => 'https://via.placeholder.com/400x200.png/008811?text=eum',
                'price' => 85.47,
                'stock' => 9,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            40 => 
            array (
                'id' => 41,
                'shop_id' => NULL,
                'cat_id' => 8,
                'child_cat_id' => 20,
                'name' => 'Voluptatem neque repudiandae.',
                'slug' => 'earum-quibusdam-aut-veniam-nesciunt-earum-provident',
                'summary' => 'Molestiae molestiae neque qui quo a id rerum eveniet ut.',
                'description' => 'Sunt repellat odio vel voluptatibus debitis velit provident. Asperiores aut distinctio qui molestiae amet veniam et. Laborum quibusdam pariatur et et. Dicta harum officiis culpa unde est qui sunt.',
                'image' => 'https://via.placeholder.com/400x200.png/00bbbb?text=optio',
                'images' => 'https://via.placeholder.com/400x200.png/00aa77?text=hic',
                'price' => 80.88,
                'stock' => 9,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            41 => 
            array (
                'id' => 42,
                'shop_id' => NULL,
                'cat_id' => 8,
                'child_cat_id' => 15,
                'name' => 'Dignissimos repellat cum.',
                'slug' => 'alias-alias-voluptatem-eveniet',
                'summary' => 'Optio non et omnis asperiores sint non minima debitis delectus.',
                'description' => 'Accusamus facere ut inventore neque reprehenderit dolorum. Fugiat beatae possimus sit quo quo est ipsum. Autem animi et atque voluptate dicta.',
                'image' => 'https://via.placeholder.com/400x200.png/00aa77?text=rerum',
                'images' => 'https://via.placeholder.com/400x200.png/0033bb?text=maiores',
                'price' => 96.17,
                'stock' => 10,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            42 => 
            array (
                'id' => 43,
                'shop_id' => NULL,
                'cat_id' => 8,
                'child_cat_id' => 7,
                'name' => 'Perferendis id nostrum.',
                'slug' => 'et-consequatur-sint-consequatur-illum-sint-similique-eveniet',
                'summary' => 'Et sit reprehenderit maiores facilis autem numquam voluptatem cum est.',
                'description' => 'Deleniti ut ad facere commodi et aliquid quis. Voluptatem sit dolorem et occaecati minima est impedit. Sit beatae ut laudantium sunt eligendi quos minus. Amet sit nostrum laborum atque.',
                'image' => 'https://via.placeholder.com/400x200.png/007766?text=similique',
                'images' => 'https://via.placeholder.com/400x200.png/000022?text=maxime',
                'price' => 75.81,
                'stock' => 10,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            43 => 
            array (
                'id' => 44,
                'shop_id' => NULL,
                'cat_id' => 1,
                'child_cat_id' => 3,
                'name' => 'Quam iste vel.',
                'slug' => 'aut-consequatur-suscipit-dolorum-atque-eum-aut-nihil',
                'summary' => 'Repudiandae laboriosam quia voluptatem laborum laborum tempora sit tenetur eum.',
                'description' => 'Eveniet nemo voluptatem dolorem ut magni omnis. Ut ut nesciunt consectetur cum voluptatem fugiat at. Occaecati non ut tempore est laborum. Culpa cupiditate nemo odio ut odit minus nam saepe. Et animi autem rerum pariatur soluta vel sequi itaque.',
                'image' => 'https://via.placeholder.com/400x200.png/004433?text=sed',
                'images' => 'https://via.placeholder.com/400x200.png/0000dd?text=similique',
                'price' => 42.7,
                'stock' => 8,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            44 => 
            array (
                'id' => 45,
                'shop_id' => NULL,
                'cat_id' => 11,
                'child_cat_id' => 2,
                'name' => 'Corrupti cupiditate maiores.',
                'slug' => 'fugiat-et-natus-et-dolorem-maiores-fugit',
                'summary' => 'Molestiae quibusdam perferendis dolorum odio autem quo cum consequatur commodi.',
                'description' => 'Debitis error vel eius odio. Voluptas laudantium atque enim. Nemo ut dolorum ab rerum ut tempore ullam voluptatem. Aut voluptas et est molestiae et temporibus veritatis.',
                'image' => 'https://via.placeholder.com/400x200.png/009988?text=aliquam',
                'images' => 'https://via.placeholder.com/400x200.png/002211?text=earum',
                'price' => 38.13,
                'stock' => 9,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            45 => 
            array (
                'id' => 46,
                'shop_id' => NULL,
                'cat_id' => 1,
                'child_cat_id' => 17,
                'name' => 'Distinctio quasi placeat.',
                'slug' => 'aliquam-quia-rem-aliquam',
                'summary' => 'Eveniet veniam non culpa et adipisci doloribus saepe ad reprehenderit.',
                'description' => 'In est earum minima illum qui. Voluptas consequatur blanditiis deserunt praesentium voluptas. Aperiam quos placeat sed reiciendis deserunt impedit.',
                'image' => 'https://via.placeholder.com/400x200.png/00ff77?text=alias',
                'images' => 'https://via.placeholder.com/400x200.png/0022dd?text=ut',
                'price' => 65.01,
                'stock' => 9,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            46 => 
            array (
                'id' => 47,
                'shop_id' => NULL,
                'cat_id' => 6,
                'child_cat_id' => 9,
                'name' => 'Natus nisi adipisci.',
                'slug' => 'laboriosam-ipsum-aut-rerum-rerum',
                'summary' => 'Ut cum voluptatem sed qui quae eos culpa aut quod.',
                'description' => 'Enim ut perferendis necessitatibus distinctio quam voluptas. Expedita fugit exercitationem dolor magni molestias sunt nemo sapiente. Voluptas consequatur saepe aut officia.',
                'image' => 'https://via.placeholder.com/400x200.png/00ff99?text=maxime',
                'images' => 'https://via.placeholder.com/400x200.png/00ff22?text=voluptatem',
                'price' => 96.74,
                'stock' => 8,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            47 => 
            array (
                'id' => 48,
                'shop_id' => NULL,
                'cat_id' => 11,
                'child_cat_id' => 15,
                'name' => 'Quibusdam nemo adipisci.',
                'slug' => 'expedita-aut-sint-illo-maxime',
                'summary' => 'Quisquam delectus sed sed vitae odio corporis nesciunt consequuntur deleniti.',
                'description' => 'Omnis sapiente cumque velit odit et. Quo provident iure dicta et. Maxime aut ad quia corporis. Magnam veniam ipsum eaque ut et asperiores corporis eum.',
                'image' => 'https://via.placeholder.com/400x200.png/008888?text=expedita',
                'images' => 'https://via.placeholder.com/400x200.png/00bb22?text=sint',
                'price' => 64.47,
                'stock' => 10,
                'condition' => 'none',
                'publish' => 0,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            48 => 
            array (
                'id' => 49,
                'shop_id' => NULL,
                'cat_id' => 10,
                'child_cat_id' => 19,
                'name' => 'Cum quisquam consequatur.',
                'slug' => 'aut-ab-laudantium-optio',
                'summary' => 'Sed sed consequatur ad neque fugit quia molestiae possimus voluptates.',
                'description' => 'Quasi quia quisquam sit similique. Laborum officiis adipisci vel enim et dolorem dicta. Ut est id est deserunt.',
                'image' => 'https://via.placeholder.com/400x200.png/009988?text=ut',
                'images' => 'https://via.placeholder.com/400x200.png/000066?text=aut',
                'price' => 88.87,
                'stock' => 10,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
            49 => 
            array (
                'id' => 50,
                'shop_id' => NULL,
                'cat_id' => 16,
                'child_cat_id' => 18,
                'name' => 'Dolor voluptate qui.',
                'slug' => 'cumque-cumque-suscipit-eos-pariatur',
                'summary' => 'Nihil et et labore quod asperiores omnis maiores natus asperiores.',
                'description' => 'Exercitationem ut a sequi dolores tempore placeat cumque. Perferendis aliquid similique aut ex fugit quasi ut. Rerum officia rerum consequatur rem quisquam et sint optio. Nisi doloribus inventore reprehenderit aut.',
                'image' => 'https://via.placeholder.com/400x200.png/00aadd?text=voluptas',
                'images' => 'https://via.placeholder.com/400x200.png/00dd00?text=et',
                'price' => 50.44,
                'stock' => 2,
                'condition' => 'none',
                'publish' => 1,
                'created_at' => '2021-06-18 17:01:44',
                'updated_at' => '2021-06-18 17:01:44',
            ),
        ));
        
        
    }
}